### ISSUE TITLE
reply for github letter?

### ISSUE THREAD

**Issue by vn971** [nickkolok/burokr-texts#1]
Was there any reply to this letter? https://github.com/nickkolok/burokr-texts/blob/master/fsf/github-2017-03-01.txt

Please update the issue once a reply will arrive.
(If you don't mind such a use of issue tracking system, anyway.. I'll get an email that way.)

**Comment by nickkolok** [comment]
The only reply was standard reply approving that my letter has been received and registered.
It's registration number is `[gnu.org #1198534]`

**Comment by nickkolok** [comment]
@vn971, I've just received a letter from FSF.
They've written a detailed post about it: https://www.fsf.org/blogs/licensing/do-githubs-updated-terms-of-service-conflict-with-copyleft

**Comment by vn971** [comment]
@nickkolok thanks for the info!
